# boilerplate code generated by claude.ai sonnet 4
# actual code by Berry
library(shiny)
library(pbapply)
library(berryFunctions)

# Define UI
ui <- fluidPage(
  titlePanel("Power Analysis for Paired t-test"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("delta","Effect Size (delta):",    min=0.1 , max=3   , value=0.5 , step=0.1 ),
      sliderInput("sd","Standard Deviation:",        min=0.1 , max=3   , value=0.8 , step=0.1 ),
      sliderInput("sig_level","Significance Level:", min=0.01, max=0.10, value=0.05, step=0.01),
      sliderInput("power","Power:",                  min=0.76, max=0.96, value=0.90, step=0.01),
    ),
    mainPanel(
      plotOutput("powerPlot", height="600px"),
      br(),
      verbatimTextOutput("sampleSize")
    )
  )
)

# Define server logic
server <- function(input, output) {
 # Run Monte Carlo simulation once at startup
 posnorm <- function(mean,sd) {res <- -1; while(res<0.02) res <- rnorm(1,mean,sd); return(res)}
 nsim <- pbapply::pbreplicate(5e3, power.t.test(
                                    delta    =posnorm(0.5, 0.5), 
                                    sd       =posnorm(0.8, 0.5), 
                                    sig.level=runif(1, 0.01, 0.10), 
                                    power    =rbeta(1, 19, 3), 
                                    type="paired", alternative="one.sided")$n)
  # Reactive calculation for theoretical sample size
  n_theoretical <- reactive({
    power.t.test(delta    =input$delta, 
                 sd       =input$sd, 
                 sig.level=input$sig_level, 
                 power    =input$power, 
                 type="paired", alternative="one.sided")$n
  })
  # Generate plot
  output$powerPlot <- renderPlot({
   berryFunctions::logHist(nsim, breaks=50, main="needed study size", xlab="n")
   abline(v=log10(n_theoretical()), col="blue", lwd=4)
  })
  
  # Display theoretical sample size
  output$sampleSize <- renderText({round(n_theoretical(), 0)})
}

# Run the application
shinyApp(ui=ui, server=server)
